### ISSUE TITLE
Installing aggiedown on windows 8 

### ISSUE THREAD

**Issue by ugull1** [ryanpeek/aggiedown#4]
Hi Ryan
I receive the following error while installing aggiedown on windows 8.

Downloading GitHub repo ryanpeek/aggiedown@master
  √  checking for file 'C:\Users\UMAIR\AppData\Local\Temp\RtmpIdoZL4\remotes1bcc666b20\ryanpeek-aggiedown-d6add79/DESCRIPTION' (24.5s)
-  preparing 'aggiedown': (12.8s)
√  checking DESCRIPTION meta-information (1.3s)
-  checking whether 'INDEX' is up-to-date ...Warning in file(con, "r") : cannot open file 'INDEX': Permission denied (552ms)
   Error in file(con, "r") : cannot open the connection
   Execution halted
 Show Traceback
Error in processx::run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout), : System command error

Regards
Umair Gull
![error](https://user-images.githubusercontent.com/35118216/52667987-2ffd2680-2ec7-11e9-98a9-987a28fdbadb.JPG)

**Comment by ryanpeek** [comment]
Hi @ugull1 , thanks for posting the issue. I updated a couple of things in the `aggiedown` package since we talked today, so I'd be interested to see if you can now install without any issues. I was able to get `aggiedown` working on both a windows 10 and windows 7 system, with successful install and knitting of the pdf.  I used the tinytex package, with the most updated R/RStudio, and I did have to copy the fonts over to my fonts folder. 

Please let me know if it works. If it doesn't and it's a different error message, feel free to file another issue...it will help me track down the source of the issue. One other possibility may be a Windows firewall or security option, but if gauchodown worked, then I doubt that is the issue. Good luck!

**Comment by ugull1** [comment]
Hi @ryanpeek 
Thankyou for updating the package.
Finally, I was able to install the package successfully on windows 8 too.
Thankyou again for your hardwork putting this great template together. 
Regards,
Umair Gull

**Comment by ryanpeek** [comment]
Excellent 👍!  Thanks.
